version: '3.1'

services:
  php:
    build:
      context: ./docker/php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    container_name: php_sa

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx_sa
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      #- ./docker/nginx/logs:/var/log/nginx
    ports:
      - "666:80"
    depends_on:
      - php

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_sa
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - 3306:3306
